STICKER_win = [
    'CAACAgIAAxkBAAEIrDFkQrIHkV73RN6q5PFZ5dO4H9d9dQACVBcAAqC6YUrGhkIfq9VhZC8E',
    'CAACAgIAAxkBAAEIrZNkQ5nyOsDvejaBLCRv4-Yrk2vZvgACzxoAApJwYUqAEgXSNoVkJS8E',
    'CAACAgIAAxkBAAEIrZZkQ5oEp8fEFVc3SlN1eDoFW8EbAwACbBsAAsmciUqDFVSLdcPqYy8E',
    'CAACAgIAAxkBAAEIrZxkQ5p_4CXAH2ePyNp_-AwGnhjp-QACvxYAAuWU8Em90itcq-sMDC8E',
    'CAACAgIAAxkBAAEIrapkQ5xItuXtzbCU8sIj4RImvpzukwACsB8AAsna0EqKnaNDLPuKoC8E',
    'CAACAgIAAxkBAAEIraxkQ5xj_3fcc_v6x7EOM6rvcLVtbQACUCYAAgxiaUnFMFmc2-cTuC8E'
]


STICKER_ARTHAS_jackpot = [
    'CAACAgIAAxkBAAEIrZBkQ5nVC3H6hH1DZehYrXDcqjOaLQAChx8AAuXCYUoHKyoKDvjMqS8E',
    'CAACAgIAAxkBAAEIrZhkQ5oez5zCbRQtT4d27SoBviairwACKhgAAomgYEomgzvcXz7qJS8E',
    'CAACAgIAAxkBAAEIrZpkQ5o7jcPMCsCtwR-VeWncGLhuVwACihsAAr54YUrZeUbhBkR97y8E',
    'CAACAgIAAxkBAAEIrZ5kQ5rdF3qc11vzxxLedwYn6ZJ0XAACAgEAAu_DGzJ1aC9BwvsI5y8E',
    'CAACAgIAAxkBAAEIraBkQ5rxfJ4Jyj_KaNKzG4z54PkKGQACBQEAAu_DGzJivflzyUxU1C8E'
]

STICKER_NO_MONEY = [
    'CAACAgIAAxkBAAEIraJkQ5s7-PjYcHTBrVqXpTR_qA8jlQACjBoAAkfVkUqo_IRBs3-Q7S8E',
    'CAACAgIAAxkBAAEIraZkQ5vsZ_pbP73zYclKzxKsYg7PdAACRhcAAp8U0Uqi3D9sszgdBy8E',
    'CAACAgIAAxkBAAEIrahkQ5wyG-4FySYfX9l_DPahyXOxRAAC3BQAAnWf4EtIjabVCNG-Pi8E'
]
